import { chromium } from 'playwright';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const DLD_URL='https://dubailand.gov.ae/en/MyDLD/#/login/sso';
const SECONDARY_PERMIT='150273';
const LOCAL_ROOT=process.env.JNA_LOCAL_DATA_DIR||path.join(os.homedir(),'.jna-permit-bot');
const PROFILE_DIR=process.env.DLD_PROFILE_DIR||path.join(LOCAL_ROOT,'chrome-profile');
const SESSION_PATH=process.env.DLD_SESSION_PATH||path.join(LOCAL_ROOT,'dld-storage.json');

const UNIT_AREA_INPUT='#ctl00_MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_AreaListRadComboBox_Input';
const UNIT_AREA_DROPDOWN='#ctl00_MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_AreaListRadComboBox_DropDown';
const LISTING_PROPERTY_RADIO='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertyAction_BodyTemplateContainer_UCPropertyActionObj_listingTypeRbl_2';
const RENT_PURPOSE_RADIO='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertyAction_BodyTemplateContainer_UCPropertyActionObj_ListingPurposeRbl_0';
const SALE_PURPOSE_RADIO='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertyAction_BodyTemplateContainer_UCPropertyActionObj_ListingPurposeRbl_1';
const LISTING_PROCEED_BUTTON='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertyAction_BodyTemplateContainer_UCPropertyActionObj_ActionButton';
const ADD_PROPERTY_BUTTON='#MainContent_UCPermitHeader_UCPropertyList1_AddPropertyButton';
const UNIT_TAB_LABEL='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UnitLabel';
const UNIT_VALUE_INPUT='#ctl00_MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_PermitPurpose_ValueTextBox';
const UNIT_LAND_INPUT='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_SearchLandNumberTextBox';
const UNIT_BUILDING_INPUT='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_SearchBuildingNameTextBox';
const UNIT_NO_INPUT='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_SearchPropertyTextBox';
const UNIT_SEARCH_BUTTON='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_SearchButton';
const MARKETING_FILE_INPUT='#ctl00_MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_UCPermitDocuments_DocumentsRadGrid_ctl00_ctl04_DocumentsRadAsyncUploadfile0';
const ADVERTISEMENT_FILE_INPUT='#ctl00_MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_UCPermitDocuments_DocumentsRadGrid_ctl00_ctl06_DocumentsRadAsyncUploadfile0';
const UNIT_SAVE_BUTTON='#MainContent_UCPermitHeader_UCPropertyList1_UCPopUpPropertiesTypes_BodyTemplateContainer_UCPropertiesTypes1_PropertyTabContainer_UnitTab_UCUnitDetails_SaveButton';

let context,page;

const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function firstVisible(p,selectors){for(const s of selectors){const l=p.locator(s).first();try{if(await l.isVisible({timeout:1200}))return l;}catch{}}return null;}
async function pageText(p){return(await p.locator('body').innerText({timeout:3000}).catch(()=>'' )).toLowerCase();}
async function saveSession(){try{fs.mkdirSync(path.dirname(SESSION_PATH),{recursive:true});await context.storageState({path:SESSION_PATH});}catch(e){console.error('Could not save session:',e.message);}}
function clearLocks(){for(const n of['SingletonLock','SingletonSocket','SingletonCookie']){try{fs.rmSync(path.join(PROFILE_DIR,n),{force:true});}catch{}}}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function esc(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}

async function inputNearLabel(label){const lab=page.getByText(new RegExp(`^${esc(label)}\\s*\\*?$`,'i')).first();if(await lab.count().catch(()=>0)){const container=lab.locator('xpath=ancestor::*[self::div or self::td or self::label][1]');let input=container.locator('input,textarea').first();if(await input.count())return input;input=lab.locator('xpath=following::input[1]');if(await input.count())return input;}return null;}
async function visibleInputNearLabel(label){const lab=page.getByText(new RegExp(`^${esc(label)}\\s*\\*?$`,'i')).first();if(!(await lab.count().catch(()=>0)))return null;const following=lab.locator('xpath=following::input[not(@type="hidden") or not(@type)][1] | following::textarea[1]');if(await following.count().catch(()=>0)){const input=following.first();if(await input.isVisible({timeout:1000}).catch(()=>false))return input;}const fallback=await inputNearLabel(label);if(fallback&&await fallback.isVisible({timeout:800}).catch(()=>false))return fallback;return null;}
async function visibleValueInput(){const exact=page.locator(UNIT_VALUE_INPUT).first();if(await exact.isVisible({timeout:1400}).catch(()=>false))return exact;return visibleInputNearLabel('Value');}

async function ensureSession(){if(context&&page&&!page.isClosed())return;fs.mkdirSync(PROFILE_DIR,{recursive:true});clearLocks();context=await chromium.launchPersistentContext(PROFILE_DIR,{channel:'chrome',headless:false,viewport:{width:1440,height:900},args:['--start-maximized']});page=context.pages()[0]||await context.newPage();page.setDefaultTimeout(10000);}

async function selectBestPage(){if(!context)return false;const pages=context.pages().filter(p=>!p.isClosed());if(!pages.length)return false;const scored=[];for(const p of pages){const url=(p.url()||'').toLowerCase(),text=await pageText(p);let score=0;if(url.includes('trakheesi.dubailand.gov.ae')){score=120;if(text.includes('transaction #')&&text.includes(SECONDARY_PERMIT))score+=150;if(await p.locator(UNIT_VALUE_INPUT).isVisible({timeout:250}).catch(()=>false))score+=180;else if(await p.locator(UNIT_AREA_INPUT).isVisible({timeout:250}).catch(()=>false))score+=130;else if(await p.locator(LISTING_PROPERTY_RADIO).isVisible({timeout:250}).catch(()=>false))score+=90;else if(await p.locator(ADD_PROPERTY_BUTTON).isVisible({timeout:250}).catch(()=>false))score+=60;}else if(text.includes('multiple profiles found')||text.includes('real estate office admin'))score=100;else if(text.includes('dld application dashboard')||text.includes('trakheesi'))score=90;else if(text.includes('login to uae pass')||text.includes('emirates id, email, or phone')||url.includes('uaepass'))score=80;else if(text.includes("i'm not a robot")||text.includes('recaptcha')||(await p.locator('iframe[src*="recaptcha"],iframe[title*="recaptcha" i]').count().catch(()=>0))>0)score=70;else if(await p.locator('input[type="password"]').count().catch(()=>0))score=60;else if(url.includes('dubailand.gov.ae'))score=50;else if(url!=='about:blank')score=10;scored.push({p,score});}scored.sort((a,b)=>b.score-a.score);if(scored[0]?.score>0){page=scored[0].p;page.setDefaultTimeout(10000);return true;}return false;}

async function currentTransactionNumber(){const raw=await page.locator('body').innerText({timeout:4000}).catch(()=>'' );const direct=raw.match(/Transaction\s*#\s*:?\s*([0-9]+)/i)?.[1];if(direct)return direct;const labels=page.getByText(/Transaction\s*#/i);for(let i=0;i<Math.min(await labels.count().catch(()=>0),8);i++){const el=labels.nth(i);if(!(await el.isVisible().catch(()=>false)))continue;const nearby=await el.locator('xpath=ancestor::*[self::tr or self::div or self::section][1]').innerText().catch(()=>'' );const n=nearby.match(/Transaction\s*#\s*:?\s*([0-9]+)/i)?.[1];if(n)return n;if(new RegExp(`(?:^|\\D)${SECONDARY_PERMIT}(?:\\D|$)`).test(nearby))return SECONDARY_PERMIT;}return null;}
async function isSecondaryPermitWorkspace(){if(!page?.url?.().includes('trakheesi.dubailand.gov.ae'))return false;const tx=await currentTransactionNumber();if(tx!==SECONDARY_PERMIT)return false;const raw=await page.locator('body').innerText({timeout:2500}).catch(()=>'' );return /Electronic\s+Advertisement\s*\/\s*Inside\s+Dubai/i.test(raw)||/Transaction\s*Type/i.test(raw);}

function areaScore(expected,candidate){const e=norm(expected),c=norm(candidate);if(!e||!c)return 0;if(e===c)return 1;if(e.startsWith(c+' '))return .99;if(e.includes(c))return .98;if(c.includes(e))return .94;const et=e.split(' '),ct=c.split(' ');let prefix=0;while(prefix<et.length&&prefix<ct.length&&et[prefix]===ct[prefix])prefix++;if(prefix>=2)return .97;if(prefix===1)return .84;const es=new Set(et),cs=new Set(ct);let shared=0;for(const t of cs)if(es.has(t))shared++;const precision=shared/Math.max(cs.size,1),recall=shared/Math.max(es.size,1);return precision&&recall?(2*precision*recall)/(precision+recall):0;}
async function selectArea(area){const input=page.locator(UNIT_AREA_INPUT).first(),dropdown=page.locator(UNIT_AREA_DROPDOWN).first();if(!(await input.count().catch(()=>0)))return false;const already=norm(await input.inputValue().catch(()=>''));if(already===norm(area))return true;for(let attempt=1;attempt<=4;attempt++){await input.click({force:true}).catch(()=>{});const combo=input.locator('xpath=ancestor::*[contains(@class,"RadComboBox")][1]');const arrow=combo.locator('.rcbActionButton,.rcbArrowCell,a').last();if(await arrow.count().catch(()=>0))await arrow.click({force:true}).catch(()=>{});await wait(450+attempt*150);const items=dropdown.locator('li.rcbItem,li.rcbHovered'),candidates=[];for(let i=0;i<await items.count().catch(()=>0);i++){const el=items.nth(i);const txt=(await el.innerText().catch(()=>'' )).replace(/\s+/g,' ').trim();if(!txt||/^all$/i.test(txt))continue;candidates.push({el,txt,score:areaScore(area,txt)});}candidates.sort((a,b)=>b.score-a.score);const best=candidates[0],second=candidates[1];if(best&&best.score>=.72&&!(second&&best.score<.95&&best.score-second.score<.06)){await input.fill(best.txt).catch(()=>{});let exact=dropdown.locator('li.rcbItem,li.rcbHovered').filter({hasText:new RegExp(`^${esc(best.txt)}$`,'i')}).first();if(!(await exact.count().catch(()=>0)))exact=best.el;await exact.evaluate(el=>el.click()).catch(async()=>exact.click({force:true}).catch(()=>{}));await wait(500);const selected=norm(await input.inputValue().catch(()=>''));if(selected===norm(best.txt)||selected.includes(norm(best.txt)))return true;}if(attempt<4)await wait(700);}return false;}

async function switchToUaePass(){if(!context)return false;for(const p of [...context.pages()].reverse()){if(p.isClosed())continue;const url=(p.url()||'').toLowerCase(),text=await pageText(p);if(url.includes('uaepass')||text.includes('login to uae pass')||text.includes('emirates id, email, or phone')){page=p;page.setDefaultTimeout(10000);return true;}}return false;}
function challenge(text){for(const r of[/(?:number|code|match|matching|shown|displayed)[^0-9]{0,100}([0-9]{2,3})/i,/([0-9]{2,3})[^0-9]{0,100}(?:number|code|match|matching|shown)/i]){const m=text.match(r);if(m)return m[1];}return null;}

async function selectAdmin(){const raw=await page.locator('body').innerText({timeout:5000}).catch(()=>'' );if(!/multiple profiles found/i.test(raw))return null;const admin=page.getByText(/REAL ESTATE OFFICE ADMIN/i).first();if(!(await admin.isVisible({timeout:4000}).catch(()=>false)))return{status:'real_estate_admin_profile_not_found',url:page.url()};const card=admin.locator('xpath=ancestor::*[.//input[@type="radio"]][1]');let radio=card.locator('input[type="radio"]').first();if(!(await radio.count()))radio=admin.locator('xpath=following::input[@type="radio"][1]');if(!(await radio.count()))return{status:'admin_profile_radio_not_found',url:page.url()};await radio.check({force:true});const proceed=await firstVisible(page,['button:has-text("Proceed")','button:has-text("Continue")','button:has-text("Submit")','button:has-text("Next")','button[type="submit"]']);if(proceed){await proceed.click({noWaitAfter:true}).catch(()=>{});await wait(3000);}await saveSession();return{status:'real_estate_admin_profile_selected',url:page.url()};}

async function submitUaePassId(){await switchToUaePass();const eid=process.env.UAE_PASS_EMIRATES_ID;if(!eid)return{status:'uae_pass_id_required',url:page.url()};const input=await firstVisible(page,['input[placeholder*="Emirates ID, email, or phone" i]','input[placeholder*="Emirates ID" i]','input[aria-label*="Emirates ID" i]','input[type="text"]','input[type="tel"]']);if(!input)return{status:'uae_pass_id_field_not_found',url:page.url()};await input.fill(eid);const btn=await firstVisible(page,['button:has-text("Login")','button:has-text("Sign in")','button[type="submit"]','input[type="submit"]']);if(!btn)return{status:'uae_pass_login_button_not_found',url:page.url()};await btn.click({noWaitAfter:true});await wait(3000);return waitForUaePassApproval(await detectState());}

async function handleUaePassModal(){const modal=page.locator('#application-infoUAE').first();if(!(await modal.isVisible({timeout:1200}).catch(()=>false)))return null;const candidates=modal.locator('button,a,[role="button"],input[type="button"],input[type="submit"],.btn,[onclick]');let target=null;for(let i=0;i<await candidates.count();i++){const el=candidates.nth(i);if(!(await el.isVisible().catch(()=>false)))continue;const label=((await el.innerText().catch(()=>''))+' '+(await el.getAttribute('value').catch(()=>''))).trim();if(/uae\s*pass/i.test(label)&&!/stay\s+on\s+dashboard/i.test(label)){target=el;break;}}if(!target)return{status:'uae_pass_modal_button_not_found',url:page.url()};const popup=context.waitForEvent('page',{timeout:5000}).catch(()=>null);await target.click({force:true,noWaitAfter:true});const p=await popup;if(p){page=p;page.setDefaultTimeout(10000);}await wait(2200);await switchToUaePass();return submitUaePassId();}

async function detectState(){await selectBestPage();if(await isSecondaryPermitWorkspace()){await saveSession();return{status:'session_active',url:page.url(),permit:SECONDARY_PERMIT};}const raw=await page.locator('body').innerText({timeout:5000}).catch(()=>''),text=raw.toLowerCase(),url=page.url();if(/multiple profiles found/i.test(raw))return selectAdmin();const c=challenge(raw);if(c)return{status:'uae_pass_approval_required',challenge:c,url};const captcha=text.includes("i'm not a robot")||text.includes('recaptcha')||(await page.locator('iframe[src*="recaptcha"],iframe[title*="recaptcha" i]').count().catch(()=>0))>0;if(captcha)return{status:'captcha_required',url};if(text.includes('login to uae pass')||text.includes('emirates id, email, or phone')||url.toLowerCase().includes('uaepass'))return{status:'uae_pass',url};const modal=await handleUaePassModal().catch(()=>null);if(modal)return modal;if(text.includes('dld application dashboard')||text.includes('trakheesi')||url.includes('trakheesi.dubailand.gov.ae')){await saveSession();return{status:'session_active',url};}if(text.includes('authentication code'))return{status:'authentication_code',url};if(await page.locator('input[type="password"]').count().catch(()=>0))return{status:'login_form',url};return{status:'post_login_unknown',url,title:await page.title().catch(()=>'' )};}
async function waitForUaePassApproval(initial){if(initial?.status!=='uae_pass_approval_required')return initial;const number=initial.challenge;const deadline=Date.now()+90000;while(Date.now()<deadline){await wait(2000);const s=await detectState();if(s.status!=='uae_pass_approval_required'||s.challenge!==number)return s;}return{...initial,status:'uae_pass_approval_timeout',challenge:number};}

async function clickTrakheesi(){const t=page.getByText('Trakheesi',{exact:true}).first();if(!(await t.isVisible({timeout:5000}).catch(()=>false)))return{status:'trakheesi_not_found',url:page.url()};const card=t.locator('xpath=ancestor::*[.//*[contains(normalize-space(.),"Go to Account")] or .//*[contains(normalize-space(.),"Login with UAE Pass")]][1]');let btn=card.getByText(/Go to Account/i,{exact:true}).first();if(await btn.isVisible({timeout:1500}).catch(()=>false)){const popup=context.waitForEvent('page',{timeout:4000}).catch(()=>null);await btn.click({force:true,noWaitAfter:true});const p=await popup;if(p){page=p;page.setDefaultTimeout(10000);}await wait(3000);await selectBestPage();if(page.url().includes('trakheesi.dubailand.gov.ae')){await saveSession();return{status:'session_active',url:page.url()};}return detectState();}btn=card.getByRole('button',{name:/login with uae pass/i}).first();if(!(await btn.isVisible().catch(()=>false)))btn=card.getByText(/login with uae pass/i).first();if(!(await btn.isVisible().catch(()=>false)))return{status:'trakheesi_account_button_not_found',url:page.url()};await btn.click({noWaitAfter:true});await wait(900);return(await handleUaePassModal())||detectState();}
async function ensureTrakheesiAccount(){await selectBestPage();if(page.url().includes('trakheesi.dubailand.gov.ae'))return{status:'session_active',url:page.url()};const text=await pageText(page);if(text.includes('dld application dashboard')&&text.includes('trakheesi')){const entered=await clickTrakheesi();await wait(1200);await selectBestPage();if(page.url().includes('trakheesi.dubailand.gov.ae'))return{status:'session_active',url:page.url()};return entered;}return{status:'trakheesi_session_required',url:page.url()};}

async function clickSecondaryPermitEditFromList(){for(let attempt=1;attempt<=5;attempt++){if(await isSecondaryPermitWorkspace())return{clicked:true,recovered:true};const permitNav=page.getByText('Permit',{exact:true}).first();if(await permitNav.isVisible({timeout:3000}).catch(()=>false)){await permitNav.click({force:true}).catch(()=>{});await wait(attempt===1?1000:650);}await page.waitForFunction(permit=>document.body?.innerText?.includes(permit),SECONDARY_PERMIT,{timeout:7000}).catch(()=>{});const direct=await page.evaluate(permit=>{const n=s=>(s||'').replace(/\s+/g,' ').trim();const re=new RegExp(`Permit\\s*Number\\s*${permit}(?:\\s|$)`,'i');const controls=[...document.querySelectorAll('a[title="Edit Permit"],a[id*="UserPermitDashBoardGrid_EditLinkButton"],input[title="Edit Permit"],button[title="Edit Permit"]')],c=[];for(const el of controls){let node=el;for(let d=0;d<14&&node;d++,node=node.parentElement){const text=n(node.innerText||node.textContent);if(re.test(text)&&/Electronic Advertisement/i.test(text)){c.push({el,d,len:text.length});break;}}}c.sort((a,b)=>a.d-b.d||a.len-b.len);if(!c[0])return false;c[0].el.click();return true;},SECONDARY_PERMIT).catch(()=>false);if(direct)return{clicked:true};const menuOpened=await page.evaluate(permit=>{const n=s=>(s||'').replace(/\s+/g,' ').trim();const re=new RegExp(`Permit\\s*Number\\s*${permit}(?:\\s|$)`,'i');const cards=[...document.querySelectorAll('div,li,tr,section,article')].filter(x=>{const t=n(x.innerText||x.textContent);return re.test(t)&&/Electronic Advertisement/i.test(t);}).sort((a,b)=>n(a.innerText||a.textContent).length-n(b.innerText||b.textContent).length);const card=cards[0];if(!card)return false;const controls=[...card.querySelectorAll('button,a,input,[role="button"],[onclick]')];const menu=controls.find(el=>{const t=n((el.innerText||el.textContent||'')+' '+(el.getAttribute('title')||'')+' '+(el.getAttribute('aria-label')||''));return t==='...'||/more|action|menu|option/i.test(t)||el.querySelector?.('.fa-ellipsis-h,.fa-ellipsis-v,.fa-ellipsis');})||controls.find(el=>/\.\.\./.test(n(el.innerText||el.textContent||'')));if(!menu)return false;menu.click();return true;},SECONDARY_PERMIT).catch(()=>false);if(menuOpened){await wait(400);const edits=page.getByText(/^Edit$/i,{exact:true}),visible=[];for(let i=0;i<await edits.count().catch(()=>0);i++)if(await edits.nth(i).isVisible().catch(()=>false))visible.push(edits.nth(i));if(visible.length===1){await visible[0].click({force:true});return{clicked:true,recovered:true};}}if(attempt<5)await wait(800);}return{clicked:false};}

async function openSecondaryPermitEdit(){await ensureSession();const entered=await ensureTrakheesiAccount();if(!page.url().includes('trakheesi.dubailand.gov.ae'))return entered?.status==='session_active'?{status:'trakheesi_session_required',url:page.url()}:entered;await selectBestPage();let tx=await currentTransactionNumber();if(tx===SECONDARY_PERMIT&&await isSecondaryPermitWorkspace())return{status:'secondary_permit_edit_open',permit:SECONDARY_PERMIT,url:page.url(),recovered:true};const clicked=await clickSecondaryPermitEditFromList();if(!clicked.clicked)return{status:'permit_edit_not_found',permit:SECONDARY_PERMIT,url:page.url(),reason:'self_heal_exhausted'};for(let attempt=1;attempt<=5;attempt++){await wait(attempt===1?1500:650);await selectBestPage();tx=await currentTransactionNumber();if(tx===SECONDARY_PERMIT&&await isSecondaryPermitWorkspace())return{status:'secondary_permit_edit_open',permit:SECONDARY_PERMIT,url:page.url(),recovered:true};if(tx&&tx!==SECONDARY_PERMIT)return{status:'wrong_permit_edit_page',permit:SECONDARY_PERMIT,actualTransaction:tx,url:page.url()};}return{status:'permit_page_unconfirmed',permit:SECONDARY_PERMIT,actualTransaction:tx,url:page.url()};}

async function ensureListingTypeAndPurpose(purpose){const purposeSelector=purpose==='RENT'?RENT_PURPOSE_RADIO:SALE_PURPOSE_RADIO;for(let attempt=1;attempt<=4;attempt++){let propertyRadio=page.locator(LISTING_PROPERTY_RADIO).first();if(!(await propertyRadio.isVisible({timeout:900}).catch(()=>false))){const add=page.locator(ADD_PROPERTY_BUTTON).first();if(!(await add.isVisible({timeout:3500}).catch(()=>false)))return{status:'add_property_button_not_found',url:page.url()};await add.click({force:true});await wait(850);propertyRadio=page.locator(LISTING_PROPERTY_RADIO).first();}if(!(await propertyRadio.isVisible({timeout:2200}).catch(()=>false)))return{status:'listing_type_property_not_found',url:page.url()};if(!(await propertyRadio.isChecked().catch(()=>false))){await propertyRadio.check({force:true}).catch(async()=>propertyRadio.click({force:true}).catch(()=>{}));await wait(650);}const purposeRadio=page.locator(purposeSelector).first();if(!(await purposeRadio.isVisible({timeout:4000}).catch(()=>false))){if(attempt<4){await wait(850);continue;}return{status:'listing_purpose_not_found',url:page.url()};}if(!(await purposeRadio.isChecked().catch(()=>false))){await purposeRadio.check({force:true}).catch(async()=>purposeRadio.click({force:true}).catch(()=>{}));await wait(500);}const proceed=page.locator(LISTING_PROCEED_BUTTON).first();if(await proceed.isVisible({timeout:4000}).catch(()=>false))return{status:'listing_ready_to_proceed',proceed};if(attempt<4)await wait(800);}return{status:'listing_proceed_not_found',url:page.url()};}
async function activateUnitTab(){for(let attempt=1;attempt<=5;attempt++){const area=page.locator(UNIT_AREA_INPUT).first();if(await area.isVisible({timeout:500}).catch(()=>false))return true;let label=page.locator(UNIT_TAB_LABEL).first();if(!(await label.count().catch(()=>0)))label=page.getByText(/^Unit$/i,{exact:true}).first();if(await label.count().catch(()=>0)){await label.evaluate(el=>{let t=el;for(let i=0;i<6&&t;i++,t=t.parentElement){if(t.matches?.('a,[onclick],[role="tab"],li')){t.click();return;}}el.click();}).catch(async()=>label.click({force:true}).catch(()=>{}));await wait(850);if(await area.isVisible({timeout:1600}).catch(()=>false))return true;}if(attempt<5)await wait(700);}return false;}

async function resultRowsInUnitModal(){const area=page.locator(UNIT_AREA_INPUT).first();if(!(await area.count().catch(()=>0)))return[];let root=area.locator('xpath=ancestor::*[contains(@id,"UnitTab")][1]');if(!(await root.count().catch(()=>0)))root=page.locator('body');const rows=root.locator('tr'),out=[];for(let i=0;i<await rows.count().catch(()=>0);i++){const row=rows.nth(i);if(!(await row.isVisible().catch(()=>false)))continue;const cells=row.locator('td');if((await cells.count().catch(()=>0))<2)continue;const text=(await row.innerText().catch(()=>'' )).replace(/\s+/g,' ').trim();if(!text||/Document Type|Marketing contract from the owner|Copy of the advertisement format/i.test(text))continue;out.push(row);}return out;}
async function findPropertyResultRow(unitNo){const wanted=norm(unitNo);const rows=await resultRowsInUnitModal();let firstCandidate=null;for(const row of rows){const cells=row.locator('td');const first=norm(await cells.first().innerText().catch(()=>''));const text=norm(await row.innerText().catch(()=>''));if(first===wanted)return row;if(!firstCandidate&&text&&!/name ar name en zone name/i.test(text))firstCandidate=row;}if(wanted){const exactCell=page.getByText(new RegExp(`^${esc(unitNo)}$`,'i'),{exact:true});for(let i=0;i<await exactCell.count().catch(()=>0);i++){const cell=exactCell.nth(i);if(!(await cell.isVisible().catch(()=>false)))continue;const row=cell.locator('xpath=ancestor::tr[1]');if(await row.count().catch(()=>0))return row;}}return firstCandidate;}
async function selectRenderedPropertyResult(unitNo){for(let attempt=1;attempt<=4;attempt++){const row=await findPropertyResultRow(unitNo);if(row){const selectedText=(await row.innerText().catch(()=>'' )).replace(/\s+/g,' ').trim();await row.click({force:true}).catch(async()=>row.locator('td').first().click({force:true}).catch(()=>{}));for(let w=0;w<5;w++){await wait(450);if(await visibleValueInput())return{ok:true,selectedText};}await row.evaluate(el=>el.click()).catch(()=>{});await wait(600);if(await visibleValueInput())return{ok:true,selectedText};}if(attempt<4)await wait(650);}return{ok:false};}

export async function inspectSecondaryListingState(){try{if(!page||page.isClosed())return{status:'no_active_session'};await selectBestPage();if(!page.url().includes('trakheesi.dubailand.gov.ae'))return{status:'listing_resume_not_ready',reason:'not_on_trakheesi',url:page.url()};const tx=await currentTransactionNumber();if(tx!==SECONDARY_PERMIT)return{status:'listing_resume_not_ready',reason:'wrong_transaction',actualTransaction:tx,url:page.url()};if(!(await page.locator(UNIT_AREA_INPUT).isVisible({timeout:1000}).catch(()=>false))){if(await isSecondaryPermitWorkspace())return{status:'secondary_permit_edit_open',permit:SECONDARY_PERMIT,url:page.url()};return{status:'listing_resume_not_ready',reason:'unit_modal_not_open',url:page.url()};}let value=await visibleValueInput();let selectedResult='';if(!value){const unitNo=await page.locator(UNIT_NO_INPUT).inputValue().catch(()=>'');const recovered=await selectRenderedPropertyResult(unitNo);if(recovered.ok){selectedResult=recovered.selectedText;value=await visibleValueInput();}}if(!value)return{status:'unit_listing_open',permit:SECONDARY_PERMIT,url:page.url()};if(!selectedResult){const row=await findPropertyResultRow(await page.locator(UNIT_NO_INPUT).inputValue().catch(()=>''));if(row)selectedResult=(await row.innerText().catch(()=>'' )).replace(/\s+/g,' ').trim();}return{status:'listing_value_ready',permit:SECONDARY_PERMIT,selectedResult,url:page.url()};}catch(error){return{status:'listing_resume_error',message:error.message,url:page?.url?.()||''};}}

export async function prepareSecondaryListing(payload={}){try{const {purpose,propertyType,deed={}}=payload;if(!['RENT','SALE'].includes(purpose))return{status:'invalid_listing_purpose'};if(!['LAND','BUILDING','VILLA','UNIT'].includes(propertyType))return{status:'invalid_property_type'};if(propertyType!=='UNIT')return{status:'property_type_not_mapped',propertyType};for(const key of['area','landNo','buildingName','unitNo'])if(!deed[key])return{status:'missing_deed_field',field:key};const opened=await openSecondaryPermitEdit();if(opened.status!=='secondary_permit_edit_open')return opened;let unitArea=page.locator(UNIT_AREA_INPUT).first();if(!(await unitArea.isVisible({timeout:800}).catch(()=>false))){const listingState=await ensureListingTypeAndPurpose(purpose);if(listingState.status!=='listing_ready_to_proceed')return listingState;await listingState.proceed.click({force:true});await wait(1100);if(!(await activateUnitTab()))return{status:'unit_tab_not_found',url:page.url()};unitArea=page.locator(UNIT_AREA_INPUT).first();}

// Before re-searching, inspect the live modal. DLD may already have rendered the result row from a previous attempt.
const existing=await selectRenderedPropertyResult(deed.unitNo);if(existing.ok)return{status:'property_selected',permit:SECONDARY_PERMIT,unitNo:deed.unitNo,buildingName:deed.buildingName,area:deed.area,selectedResult:existing.selectedText,url:page.url(),recovered:true};

if(!(await selectArea(deed.area)))return{status:'area_option_not_found',area:deed.area,url:page.url()};const land=page.locator(UNIT_LAND_INPUT).first(),building=page.locator(UNIT_BUILDING_INPUT).first(),unit=page.locator(UNIT_NO_INPUT).first();if(!(await land.count().catch(()=>0))||!(await building.count().catch(()=>0))||!(await unit.count().catch(()=>0)))return{status:'property_search_fields_not_found',url:page.url()};await land.fill(String(deed.landNo));await building.fill(String(deed.buildingName));await unit.fill(String(deed.unitNo));const search=page.locator(UNIT_SEARCH_BUTTON).first();if(!(await search.isVisible({timeout:5000}).catch(()=>false)))return{status:'property_search_button_not_found',url:page.url()};await search.click({force:true});
for(let attempt=1;attempt<=5;attempt++){await wait(attempt===1?1100:650);const recovered=await selectRenderedPropertyResult(deed.unitNo);if(recovered.ok)return{status:'property_selected',permit:SECONDARY_PERMIT,unitNo:deed.unitNo,buildingName:deed.buildingName,area:deed.area,selectedResult:recovered.selectedText,url:page.url(),recovered:attempt>1};}
const raw=await page.locator('body').innerText().catch(()=>'' );return{status:'property_search_no_results',url:page.url(),observedUnit:raw.includes(String(deed.unitNo))?String(deed.unitNo):null};}catch(error){return{status:'prepare_listing_error',message:error.message,url:page?.url?.()||''};}}

export async function finalizeSecondaryListing(payload={}){try{if(!page||page.isClosed())return{status:'no_active_session'};await selectBestPage();const {value,marketingContract,advertisementFormat}=payload;if(!value||!marketingContract?.path||!advertisementFormat?.path)return{status:'listing_inputs_missing'};const tx=await currentTransactionNumber();if(tx!==SECONDARY_PERMIT)return{status:'wrong_permit_edit_page',permit:SECONDARY_PERMIT,actualTransaction:tx,url:page.url()};if(!(await page.locator(UNIT_AREA_INPUT).isVisible({timeout:1000}).catch(()=>false)))return{status:'listing_resume_not_ready',reason:'unit_modal_not_open',url:page.url()};const valueInput=await visibleValueInput();if(!valueInput)return{status:'value_field_not_found',url:page.url()};await valueInput.fill(String(value));let marketingInput=page.locator(MARKETING_FILE_INPUT).first(),adInput=page.locator(ADVERTISEMENT_FILE_INPUT).first();if(!(await marketingInput.count().catch(()=>0))||!(await adInput.count().catch(()=>0))){const rows=page.locator('table tr');marketingInput=null;adInput=null;for(let i=0;i<await rows.count();i++){const row=rows.nth(i),txt=(await row.innerText().catch(()=>'' )).toLowerCase();if(txt.includes('marketing contract from the owner'))marketingInput=row.locator('input[type="file"]').first();if(txt.includes('copy of the advertisement format'))adInput=row.locator('input[type="file"]').first();}}if(!marketingInput||!(await marketingInput.count())||!adInput||!(await adInput.count()))return{status:'document_upload_fields_not_found',url:page.url()};await marketingInput.setInputFiles(marketingContract.path);await adInput.setInputFiles(advertisementFormat.path);const announcement=await visibleInputNearLabel('Announcement Text');if(announcement)await announcement.fill('');const save=page.locator(UNIT_SAVE_BUTTON).first();if(!(await save.isVisible({timeout:5000}).catch(()=>false)))return{status:'listing_save_button_not_found',url:page.url()};await save.click({force:true});await wait(2200);await saveSession();return{status:'listing_saved',permit:SECONDARY_PERMIT,url:page.url(),message:(await page.locator('body').innerText().catch(()=>'' )).slice(0,1200)};}catch(error){return{status:'finalize_listing_error',message:error.message,url:page?.url?.()||''};}}

export async function startInteractiveDldLogin(){const u=process.env.DLD_USERNAME,p=process.env.DLD_PASSWORD;if(!u||!p)return{status:'missing_credentials'};await ensureSession();await selectBestPage();if(await isSecondaryPermitWorkspace())return{status:'session_active',url:page.url(),permit:SECONDARY_PERMIT};if(page&&page.url()!=='about:blank'){const existing=await detectState();if(existing.status==='uae_pass_approval_required')return waitForUaePassApproval(existing);if(['session_active','real_estate_admin_profile_selected','uae_pass','captcha_required','login_form'].includes(existing.status))return existing;}await page.goto(DLD_URL,{waitUntil:'domcontentloaded',timeout:45000});await wait(2600);const body=await pageText(page);if(body.includes('dld application dashboard')){if(body.includes('trakheesi'))return clickTrakheesi();await saveSession();return{status:'session_active',url:page.url()};}const user=await firstVisible(page,['input[name="username"]','input[name="Username"]','input[type="text"][placeholder*="user" i]','input[type="email"]','input[type="text"]']);const pass=await firstVisible(page,['input[type="password"]']);if(!user||!pass){const recovered=await detectState();if(recovered.status!=='post_login_unknown')return recovered;return{status:'login_form_not_found',url:page.url()};}await user.fill(u);await pass.fill(p);return detectState();}
export async function continueAfterCaptcha(){if(!page||page.isClosed())return{status:'no_active_session'};try{await selectBestPage();if(await isSecondaryPermitWorkspace())return{status:'session_active',url:page.url(),permit:SECONDARY_PERMIT};const m=await handleUaePassModal();if(m)return m;const raw=await page.locator('body').innerText({timeout:5000}).catch(()=>''),body=raw.toLowerCase();if(body.includes('dld application dashboard')&&body.includes('trakheesi'))return clickTrakheesi();if(/multiple profiles found/i.test(raw))return selectAdmin();if(body.includes('login to uae pass')||body.includes('emirates id, email, or phone'))return detectState();const btn=await firstVisible(page,['button:has-text("Sign In")','input[type="submit"]','button[type="submit"]']);if(btn){await btn.click({noWaitAfter:true});await wait(3500);}return waitForUaePassApproval(await detectState());}catch(error){return{status:'continue_error',message:error.message,url:page?.url?.()||''};}}
export async function continueUaePassLogin(){if(!page||page.isClosed())return{status:'no_active_session'};try{return await submitUaePassId();}catch(error){return{status:'uae_pass_error',message:error.message,url:page?.url?.()||''};}}
export async function checkUaePassStatus(){if(!page||page.isClosed())return{status:'no_active_session'};try{await wait(900);let s=await detectState();s=await waitForUaePassApproval(s);if(['session_active','real_estate_admin_profile_selected'].includes(s.status))await saveSession();return s;}catch(error){return{status:'uae_pass_check_error',message:error.message,url:page?.url?.()||''};}}
export async function testDldLogin(){try{return await startInteractiveDldLogin();}catch(error){return{status:'agent_error',message:error.message};}}
